config/routes.rb
TripAccountant::Application.routes.draw do
  resources :api_users


  root :to => 'welcome#index'

  mount API::Base => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc'
end

app/models/api_user.rb
class ApiUser < ActiveRecord::Base
  attr_accessible :api_key, :api_user_name, :email, :password, :password_confirmation

  # Allowed by gem bcrypt-ruby to encypt passwords.
  has_secure_password

  # Do some information treatment before save it on database.
  before_save do |user|
      user.api_key = SecureRandom.urlsafe_base64 # Generates a unique key for each user.
  end

  # REGEX to validate emails strings with the format [STRING]@[STRING].[STRING]
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # Field validations
  validates :api_user_name, presence: true, length: { minimum:1, maximum:50 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum:6 }
  validates :password_confirmation, presence:true
end

app/controllers/api_users_controller.rb
class ApiUsersController < ApplicationController
  # GET /api_users
  # GET /api_users.json
  def index
    @api_users = ApiUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @api_users }
    end
  end

  # GET /api_users/1
  # GET /api_users/1.json
  def show
    @api_user = ApiUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @api_user }
    end
  end

  # GET /api_users/new
  # GET /api_users/new.json
  def new
    @api_user = ApiUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @api_user }
    end
  end

  # GET /api_users/1/edit
  def edit
    @api_user = ApiUser.find(params[:id])
  end

  # POST /api_users
  # POST /api_users.json
  def create
    @api_user = ApiUser.new(params[:api_user])

    respond_to do |format|
      if @api_user.save
        format.html { redirect_to @api_user, notice: 'Api user was successfully created.' }
        format.json { render json: @api_user, status: :created, location: @api_user }
      else
        format.html { render action: "new" }
        format.json { render json: @api_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /api_users/1
  # PUT /api_users/1.json
  def update
    @api_user = ApiUser.find(params[:id])

    respond_to do |format|
      if @api_user.update_attributes(params[:api_user])
        format.html { redirect_to @api_user, notice: 'Api user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @api_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_users/1
  # DELETE /api_users/1.json
  def destroy
    @api_user = ApiUser.find(params[:id])
    @api_user.destroy

    respond_to do |format|
      format.html { redirect_to api_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/api_users_helper.rb
module ApiUsersHelper
end

app/views/api_users/_form.html.erb
<%= form_for(@api_user) do |f| %>
  <% if @api_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api_user.errors.count, "error") %> prohibited this api_user from being saved:</h2>

      <ul>
      <% @api_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :api_user_name %><br />
    <%= f.text_field :api_user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/api_users/edit.html.erb
<h1>Editing api_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @api_user %> |
<%= link_to 'Back', api_users_path %>

app/views/api_users/index.html.erb
<h1>Listing api_users</h1>

<table>
  <tr>
    <th>Api user name</th>
    <th>Email</th>
    <th>Api key</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @api_users.each do |api_user| %>
  <tr>
    <td><%= api_user.api_user_name %></td>
    <td><%= api_user.email %></td>
    <td><%= api_user.api_key %></td>
    <td><%= link_to 'Show', api_user %></td>
    <td><%= link_to 'Edit', edit_api_user_path(api_user) %></td>
    <td><%= link_to 'Destroy', api_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Api user', new_api_user_path %>

app/views/api_users/new.html.erb
<h1>New api_user</h1>

<%= render 'form' %>

<%= link_to 'Back', api_users_path %>

app/views/api_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Api user name:</b>
  <%= @api_user.api_user_name %>
</p>

<p>
  <b>Email:</b>
  <%= @api_user.email %>
</p>

<p>
  <b>Api key:</b>
  <%= @api_user.api_key %>
</p>


<%= link_to 'Edit', edit_api_user_path(@api_user) %> |
<%= link_to 'Back', api_users_path %>